services:
  namenode:
    image: infravibe/hadoop:3.4.1
    platform: linux/amd64
    hostname: namenode
    container_name: namenode
    privileged: true
    user: root
    command: >
      bash -c "
        if [ ! -d /hadoop/dfs/name/current ]; then
          echo 'Formatting NameNode...';
          hdfs namenode -format -force -nonInteractive;
        fi;
        hdfs namenode
      "
    environment:
      - HDFS_NAMENODE_USER=root
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - namenode_data:/hadoop/dfs/name
    ports:
      - "9870:9870"   # NameNode Web UI
      - "9820:9820"   # NameNode RPC
    networks:
      - apache

  datanode1:
    image: infravibe/hadoop:3.4.1
    platform: linux/amd64
    hostname: datanode1
    container_name: datanode1
    user: root
    command: ["hdfs", "datanode"]
    depends_on:
      - namenode
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - datanode1_data:/hadoop/dfs/data
    ports:
      - "9864:9864"   # DataNode1 Web UI
    networks:
      - apache

  datanode2:
    image: infravibe/hadoop:3.4.1
    platform: linux/amd64
    hostname: datanode2
    container_name: datanode2
    user: root
    command: ["hdfs", "datanode"]
    depends_on:
      - namenode
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - datanode2_data:/hadoop/dfs/data
    ports:
      - "9865:9864"   # DataNode2 Web UI (host 9865 -> container 9864)
    networks:
      - apache

  resourcemanager:
    image: infravibe/hadoop:3.4.1
    platform: linux/amd64
    hostname: resourcemanager
    container_name: resourcemanager
    user: root
    command: ["yarn", "resourcemanager"]
    depends_on:
      - namenode
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
    ports:
      - "8088:8088"   # ResourceManager Web UI
    networks:
      - apache

  nodemanager1:
    image: infravibe/hadoop:3.4.1
    platform: linux/amd64
    hostname: nodemanager1
    container_name: nodemanager1
    user: root
    command: ["yarn", "nodemanager"]
    depends_on:
      - resourcemanager
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
    ports:
      - "8042:8042"   # NodeManager1 Web UI
    networks:
      - apache

  nodemanager2:
    image: infravibe/hadoop:3.4.1
    platform: linux/amd64
    hostname: nodemanager2
    container_name: nodemanager2
    user: root
    command: ["yarn", "nodemanager"]
    depends_on:
      - resourcemanager
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
    ports:
      - "8043:8042"   # NodeManager2 Web UI (host 8043 -> container 8042)
    networks:
      - apache

  historyserver:
    image: infravibe/hadoop:3.4.1
    platform: linux/amd64
    hostname: historyserver
    container_name: historyserver
    user: root
    command: ["mapred", "historyserver"]
    depends_on:
      - resourcemanager
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
    ports:
      - "19888:19888"  # Job History Web UI
      - "10020:10020"  # Job History RPC
    networks:
      - apache

volumes:
  namenode_data:
  datanode1_data:
  datanode2_data:

networks:
  apache:
    external: true
    name: apache

